set -g default-terminal "screen-256color"
set -g status-position top
set-option -g focus-events on

set -g detach-on-destroy off
bind x kill-pane

set-option -g prefix C-Enter
unbind-key C-b
bind-key C-Enter send-prefix

# Makes Shift + Enter work 
bind -n S-Enter send-keys Escape "[13;2u"

unbind r
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

set -g mouse on

set -g base-index 1
setw -g pane-base-index 1

setw -g mode-keys vi

bind-key -r H resize-pane -L 5
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r L resize-pane -R 5

# Sesh
bind-key -r s run-shell "sesh connect \"$(
  sesh list --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}'
)\""


# Plugins
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @minimal-tmux-justify "absolute-centre"
set -g @minimal-tmux-status "top"
set -g @minimal-tmux-fg "#f7f1ff"
set -g @minimal-tmux-bg "#3D3D3C"
set -g @minimal-tmux-use-arrow true
set -g @minimal-tmux-right-arrow ""
set -g @minimal-tmux-left-arrow ""

set -g pane-active-border-style 'fg=#fce566'

run '$HOMEBREW_PREFIX/opt/tpm/share/tpm/tpm'
