set -g default-terminal "screen-256color"
set -g status-position top
set-option -g focus-events on

set -g detach-on-destroy off
bind x kill-pane

set-option -g prefix C-Space
unbind-key C-b
bind-key C-Space send-prefix

unbind r
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

set -g mouse on

set -g base-index 1
setw -g pane-base-index 1

setw -g mode-keys vi

bind-key -r H resize-pane -L 5
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r L resize-pane -R 5


# Plugins
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @minimal-tmux-status "top"
set -g @minimal-tmux-fg "#f7f1ff"
set -g @minimal-tmux-bg "#212121"
set -g @minimal-tmux-use-arrow true
set -g @minimal-tmux-right-arrow ""
set -g @minimal-tmux-left-arrow ""

set -g pane-active-border-style 'fg=#fce566'

run '$HOMEBREW_PREFIX/opt/tpm/share/tpm/tpm'
